---
- hosts: kali01
  become: yes
  become_method: sudo
  gather_facts: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: install base packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - vim
          - net-tools
          - python3
          - unzip
          - tmux
          - nmap
          - webshells
          - ipython3 
        state: present

    - name: ensure old versions of Docker are not installed
      package:
        name:
          - docker
          - docker-engine
        state: absent
      become: true

    - name: add docker apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present

    - name: add docker repo
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
        state: present
        filename: docker
        update_cache: yes

    # - name: update apt cache
    #   apt:
    #     update_cache: yes

    - name: install docker-ce
      apt:
        name: 
            - docker-ce
            - docker-ce-cli
            - containerd.io
        state: present

    - name: add vagrant user to docker group
      user:
        name: vagrant
        group: docker

    - name: tooling dir
      file:
        path: /home/vagrant/tools/
        owner: vagrant
        group: vagrant
        state: directory

    - name: Install tooling 
      git:
        repo: "{{ item.value }}"         
        dest: "/home/vagrant/tools/{{ item.key }}"
        version: master
      with_dict:  
        - { impacket: "https://github.com/SecureAuthCorp/impacket.git" } 
        - { nishang: "https://github.com/samratashok/nishang.git" }  
        - { LinEnum: "https://github.com/rebootuser/LinEnum.git" } 
        - { PrivescCheck: "https://github.com/itm4n/PrivescCheck.git" }  
        - { evil-winrm: "https://github.com/Hackplayers/evil-winrm.git" }  
        - { dirsearch: "https://github.com/maurosoria/dirsearch.git" } 
        - { peas: "https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite.git" }
        - { seclists: "https://github.com/danielmiessler/SecLists.git" } 
        - { oh-my-tmux: "https://github.com/gpakosz/.tmux.git" } 


    - name: Remove original tmux 
      file:
        path: /home/vagrant/.tmux.conf
        state: absent 

    - name: symlink oh-my-tmux config
      file:
        src: /home/vagrant/tools/oh-my-tmux/.tmux.conf
        dest: /home/vagrant/.tmux.conf
        state: link


    - name: mkdir for pspy64
      file:
        path: /home/tools/pspy
        owner: vagrant
        group: vagrant
        state: directory       

    - name: Install pspy64
      get_url: 
        url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64
        dest: /home/vagrant/tools/pspy64
        



